-- Users / Auth
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY, -- Changed from SERIAL to INTEGER to allow syncing ID from Oracle if needed, or keep SERIAL but allow explicit insert
    legacy_user_id VARCHAR(50), -- Changed from INTEGER to VARCHAR(50)
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(500) NOT NULL, -- Changed from VARCHAR(255) to VARCHAR(500)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS roles (
    id INTEGER PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    description VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id INTEGER NOT NULL REFERENCES users(id),
    role_id INTEGER NOT NULL REFERENCES roles(id),
    PRIMARY KEY (user_id, role_id)
);

-- Paciente
CREATE TABLE IF NOT EXISTS paciente (
  cd_paciente INTEGER PRIMARY KEY,
  cd_cidade INTEGER,
  cd_dis_san INTEGER,
  tp_situacao VARCHAR(1) NOT NULL,
  nm_mnemonico VARCHAR(14),
  nm_paciente VARCHAR(40) NOT NULL,
  tp_sexo VARCHAR(1) NOT NULL,
  tp_estado_civil VARCHAR(1),
  cd_cidade_tem INTEGER,
  ds_endereco VARCHAR(100),
  dt_cadastro TIMESTAMP NOT NULL,
  dt_nascimento DATE,
  tp_cor VARCHAR(1),
  nm_mae VARCHAR(40),
  cd_cla_eco INTEGER,
  cd_cidadania INTEGER,
  cd_tip_mor INTEGER,
  cd_tip_res INTEGER,
  cd_grau_ins INTEGER,
  cd_religiao INTEGER,
  cd_profissao INTEGER,
  nr_cep VARCHAR(8),
  nr_documento VARCHAR(30),
  hr_cadastro TIMESTAMP,
  nr_fone VARCHAR(40),
  nm_bairro VARCHAR(100),
  nm_pai VARCHAR(40),
  cd_dis_san_muitos INTEGER,
  ds_trabalho VARCHAR(50),
  nm_conjuge VARCHAR(30),
  tp_sanguineo VARCHAR(3),
  sn_doador VARCHAR(1),
  ds_checapac VARCHAR(28),
  nm_usuario VARCHAR(30),
  cd_cns VARCHAR(11),
  nr_cns VARCHAR(15),
  nr_cpf VARCHAR(11),
  ds_complemento VARCHAR(30),
  nr_endereco INTEGER,
  nr_rg_nasc NUMERIC,
  nr_identidade VARCHAR(20),
  ds_om_identidade VARCHAR(8),
  ds_observacao VARCHAR(2000),
  cd_paciente_antigo VARCHAR(8),
  dt_ultima_atualizacao TIMESTAMP,
  cd_naturalidade INTEGER,
  cd_multi_empresa INTEGER NOT NULL,
  ds_atributo1 VARCHAR(150),
  sn_alt_dados_ora_app VARCHAR(1) DEFAULT 'S' NOT NULL,
  email VARCHAR(40),
  dt_inativo TIMESTAMP,
  cd_pis_pasep VARCHAR(12),
  tp_certidao VARCHAR(1),
  nm_cartorio VARCHAR(50),
  ds_livro VARCHAR(10),
  ds_folha VARCHAR(10),
  dt_emissao_certidao TIMESTAMP,
  dt_emissao_identidade TIMESTAMP,
  cd_uf_emissao_identidade VARCHAR(2),
  dt_entrada_estrangeiro TIMESTAMP,
  nr_ctps VARCHAR(10),
  nr_serie_ctps VARCHAR(10),
  dt_emissao_ctps TIMESTAMP,
  cd_uf_emissao_ctps VARCHAR(2),
  nr_titulo_eleitoral VARCHAR(15),
  nr_zona_titulo_eleitoral VARCHAR(5),
  nr_secao_titulo_eleitoral VARCHAR(5),
  sn_recebe_contato VARCHAR(1) DEFAULT 'N' NOT NULL,
  cd_paciente_integra VARCHAR(50),
  cd_seq_integra VARCHAR(20),
  dt_integra TIMESTAMP,
  cd_tipo_logradouro INTEGER,
  sn_permite_agendar_para_sus VARCHAR(1),
  cd_categoria_opiniao INTEGER,
  sn_vip VARCHAR(1) DEFAULT 'N' NOT NULL,
  cd_pais INTEGER,
  cd_paciente_externo VARCHAR(15),
  cd_etnia INTEGER,
  ds_hash VARCHAR(119),
  nr_documento_estrangeiro VARCHAR(50),
  dt_entrada_brasil TIMESTAMP,
  dt_naturalizacao TIMESTAMP,
  nr_portaria_naturalizacao VARCHAR(60),
  nr_ddd_fone INTEGER,
  nr_ddd_celular INTEGER,
  nr_celular VARCHAR(40),
  nr_ddi_fone NUMERIC,
  nr_ddi_celular NUMERIC,
  nr_ddi_fone_comercial NUMERIC,
  nr_ddd_fone_comercial INTEGER,
  nr_fone_comercial VARCHAR(40),
  sn_notificacao_sms VARCHAR(1) DEFAULT 'N' NOT NULL,
  sn_utiliza_nome_social VARCHAR(1) DEFAULT 'N',
  nm_social_paciente VARCHAR(200),
  cd_identificador_pessoa VARCHAR(50),
  sn_endereco_sem_numero VARCHAR(1) DEFAULT 'N' NOT NULL,
  cd_banco INTEGER,
  nr_agencia VARCHAR(10),
  ds_agencia VARCHAR(20),
  nr_conta VARCHAR(15),
  sn_frequenta_escola VARCHAR(1),
  ds_cargo_trabalho VARCHAR(500),
  nr_registro_funcional_trabalho VARCHAR(500),
  ds_vinclulo_trabalho VARCHAR(500),
  ds_horario_trabalho VARCHAR(4000),
  tp_paciente VARCHAR(50),
  cd_tip_paren INTEGER,
  ds_complemento_tutor VARCHAR(4000),
  nm_tutor VARCHAR(100),
  dt_nascimento_tutor TIMESTAMP,
  tp_sexo_tutor VARCHAR(1),
  nr_cpf_tutor VARCHAR(11)
);

-- Log de Unificação de Pacientes
CREATE TABLE IF NOT EXISTS log_unificacao_paciente (
    id SERIAL PRIMARY KEY,
    cd_paciente_antigo INTEGER NOT NULL,
    cd_paciente_novo INTEGER NOT NULL,
    dt_unificacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ds_observacao VARCHAR(2000)
);

-- Item Agendamento
CREATE TABLE IF NOT EXISTS item_agendamento (
  cd_item_agendamento INTEGER PRIMARY KEY,
  ds_item_agendamento VARCHAR(70) NOT NULL,
  tp_item VARCHAR(1) NOT NULL,
  cd_exa_lab INTEGER,
  cd_exa_rx INTEGER,
  cd_pro_fat VARCHAR(8),
  cd_ssm VARCHAR(8),
  hr_realizacao TIMESTAMP,
  sn_ativo VARCHAR(1) NOT NULL,
  sn_checa_guia VARCHAR(1) DEFAULT 'N' NOT NULL,
  ds_mnemonico VARCHAR(8),
  cd_procedimento_sia VARCHAR(10),
  sn_sugere_alt_tempo_anestesia VARCHAR(1) DEFAULT 'N' NOT NULL
);

-- Agenda Central
CREATE TABLE IF NOT EXISTS it_agenda_central (
     cd_agenda_central INTEGER, -- Assuming this is expected to be unique via logic or index if not PK
     hr_agenda TIMESTAMP NOT NULL,
     cd_paciente INTEGER NOT NULL REFERENCES paciente(cd_paciente),
     nm_paciente VARCHAR(200),
     vl_altura NUMERIC(10,2),
     qt_peso NUMERIC(10,3),
     dt_nascimento TIMESTAMP,
     sn_atendido VARCHAR(1) DEFAULT 'N' NOT NULL,
     sn_encaixe VARCHAR(1) DEFAULT 'N' NOT NULL,
     cd_grupo_agenda INTEGER, -- Using INTEGER instead of VARCHAR(10) based on typical FK usage, correct if wrong
     cd_atendimento INTEGER,
     cd_gru_ate INTEGER,
     cd_item_agendamento INTEGER REFERENCES item_agendamento(cd_item_agendamento),
     cd_usuario VARCHAR(30), -- Changed from INTEGER to VARCHAR(30) to match nm_usuario or ID types usually
     cd_convenio INTEGER,
     cd_con_pla INTEGER,
     cd_ser_dis INTEGER,
     cd_tip_mar INTEGER,
     tp_situacao VARCHAR(1) NOT NULL,
     vl_perc_desconto NUMERIC(5,2),
     vl_negociado NUMERIC(12,2),
     sn_anestesista VARCHAR(1) DEFAULT 'N' NOT NULL,
     sn_publico VARCHAR(1) DEFAULT 'N' NOT NULL,
     sn_bloqueado VARCHAR(1) DEFAULT 'N' NOT NULL,
     nr_fone VARCHAR(40),
     cd_anestesista INTEGER,
     ds_observacao VARCHAR(2000),
     cd_it_agenda_central INTEGER PRIMARY KEY,
     cd_it_agenda_pai INTEGER,
     tp_sexo VARCHAR(1),
     cd_solic_agendamento INTEGER,
     cd_atendimento_pai INTEGER,
     ds_senha_painel VARCHAR(20),
     sn_dispensa_equipamentos VARCHAR(1) DEFAULT 'N' NOT NULL,
     dt_gravacao TIMESTAMP,
     ds_email VARCHAR(100),
     cd_agenda_fila_espera INTEGER,
     sn_agenda_faturada VARCHAR(1) DEFAULT 'N' NOT NULL,
     ds_observacao_geral VARCHAR(2000),
     sn_sessao VARCHAR(1) DEFAULT 'N' NOT NULL,
     nr_sessao_scma NUMERIC(4,0),
     vl_tempo_realizacao_informado NUMERIC(14,0),
     hr_fim TIMESTAMP,
     cd_it_agenda_central_integra VARCHAR(50),
     cd_seq_integra VARCHAR(20),
     dt_integra TIMESTAMP,
     dh_presenca_falta TIMESTAMP,
     tp_presenca_falta VARCHAR(5),
     cd_usuario_presenca_falta VARCHAR(30),
     sn_encaixe_extra VARCHAR(1) DEFAULT 'N' NOT NULL,
     nr_celular VARCHAR(40),
     nr_ddi_telefone NUMERIC(4,0),
     nr_ddd_celular NUMERIC(4,0),
     nr_ddi_celular NUMERIC(4,0),
     nr_id_envio_sms VARCHAR(20),
     nr_ddd_fone NUMERIC(4,0),
     cd_movimento_pactuacao INTEGER,
     cd_log_opera_agenda INTEGER
);

-- Solicitacoes / Lista de Espera
CREATE TABLE IF NOT EXISTS solicitacoes (
    cd_lista_espera INTEGER PRIMARY KEY,
    cd_paciente INTEGER NOT NULL REFERENCES paciente(cd_paciente),
    cd_it_agend INTEGER REFERENCES item_agendamento(cd_item_agendamento),
    cd_atendimento INTEGER,
    cd_procedimento INTEGER,
    dt_atendimento TIMESTAMP,
    cd_prestador INTEGER,
    cd_ori_ate INTEGER,
    cd_convenio INTEGER,
    cd_multi_empresa INTEGER,
    olho VARCHAR(50),
    tp_situacao VARCHAR(1),
    observ VARCHAR(4000),
    dt_agendamento TIMESTAMP,
    dt_marcacao TIMESTAMP,
    cd_it_agenda_central INTEGER REFERENCES it_agenda_central(cd_it_agenda_central),
    nm_usuario_marc VARCHAR(30),
    dt_realizacao TIMESTAMP,
    dt_lanca_lista TIMESTAMP,
    cd_atendimento_r INTEGER,
    sn_encaixe VARCHAR(1),
    cd_documento INTEGER,
    cd_priori INTEGER,
    ds_priori VARCHAR(100),
    cd_usuario_edit VARCHAR(30),
    cd_perg_od INTEGER,
    cd_perg_oe INTEGER,
    cd_id_fila INTEGER,
    dt_retorno TIMESTAMP,
    sn_cota VARCHAR(1),
    resposta_retorno VARCHAR(4000),
    cer_periodic INTEGER,
    cer_tp_grup INTEGER,
    cer_qt_grup INTEGER,
    cer_tot_ses INTEGER,
    cer_sessao INTEGER,
    
    -- Campos Adicionais (Joins/Subqueries)
    ds_item_agendamento VARCHAR(70),
    item_agendamento_correlato TIMESTAMP,
    ds_item_agendamento_correlato VARCHAR(70),

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Logs table for Sync History
CREATE TABLE IF NOT EXISTS sync_logs (
    id SERIAL PRIMARY KEY,
    status VARCHAR(50) NOT NULL, -- SUCCESS, ERROR, INFO
    message TEXT,
    payload_summary TEXT, -- JSON or text summary of what was synced
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
